version: '3'
services:
  php:
    image: dev-docker-registry0.km.rst.com.pl:5000/libraries/php:5.6
    environment:
      INTEGRATION_DB_HOST: 'mysql'
      INTEGRATION_DB_PASSWORD: 'travis'
      INTEGRATION_DB_USER: 'travis'
      INTEGRATION_DB_NAME: 'test'
    volumes:
      - '.:/app'
    working_dir: '/app'
    links:
      - mysql
  mysql:
    image: mysql/mysql-server:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'travis'
      MYSQL_PASSWORD: 'travis'
    expose:
      - '3306'

