version: '3'
services:
  php:
    image: php:5.6-alpine
  mysql:
    image: mysql/mysql-server:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'travis'
      MYSQL_PASSWORD: ''

